# Site settings
title: Mario Ramírez
email: ramirezmario@outlook.com
url: https://MarioRamirez.github.io
description: "Sitio web de información personal acerca de Mario Ramírez."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Github y Jekyll
  location: Dirección
  social: Redes Sociales
  credits: Mentor

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://www.linkedin.com/in/mramirezm
  - title: github
    url: http://github.com/MarioRamirez

# Postal address (add as many lines as necessary)
address:
  - line: Av. Almirante Blanco Encalada 1797
  - line: Santiago - Región Metropolitana
  - line: Chile

# Credits content
credits: 'Si quieres saber más acerca de mis aptitudes profesionales puedes consultar con <a href="http://cl.linkedin.com/in/nelsonpatriciojimenez">Nelson Jiménez</a>.'

# Build settings
markdown: kramdown
permalink: pretty
